In [1]:
import tensorflow as tf

In [2]:
x = tf.constant(3)

In [5]:
x = tf.constant([3,4,5,])

In [8]:
print(tf.reshape(x,(1,3)))

tf.Tensor([[3 4 5]], shape=(1, 3), dtype=int32)


In [11]:
x2 = tf.stack([x,x])

In [12]:
print(tf.reshape(x2,(3,2)))

tf.Tensor(
[[3 4]
 [5 3]
 [4 5]], shape=(3, 2), dtype=int32)


In [13]:
w = tf.Variable(2,dtype='float',name='myVar')

In [15]:
w.assign(6)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=6.0>

In [16]:
w.assign_add(4)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=10.0>

In [18]:
w = tf.Variable([[1],[2]])
x = tf.constant([[3,2]])
tf.matmul(w,x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [6, 4]])>

In [30]:
textFileDataset = tf.data.TextLineDataset('./notes.md')

In [37]:
for file in tf.data.Dataset.list_files('.'):
    print(file)

tf.Tensor(b'.', shape=(), dtype=string)


In [31]:
for line in textFileDataset.take(6):
    print(line)

tf.Tensor(b'', shape=(), dtype=string)
tf.Tensor(b'|[Home](../README.md)|[Course Page]()|', shape=(), dtype=string)
tf.Tensor(b'|---------------------|--------------|', shape=(), dtype=string)
tf.Tensor(b'', shape=(), dtype=string)
tf.Tensor(b'## Introduction to TensorFlow', shape=(), dtype=string)
tf.Tensor(b'', shape=(), dtype=string)


In [28]:
for line in textFileDataset.take(6):
    print(line)

tf.Tensor([b'' b'|[Home](../README.md)|[Course Page]()|'], shape=(2,), dtype=string)
tf.Tensor([b'|---------------------|--------------|' b''], shape=(2,), dtype=string)
tf.Tensor([b'## Introduction to TensorFlow' b''], shape=(2,), dtype=string)
tf.Tensor([b'[TOC]' b''], shape=(2,), dtype=string)
tf.Tensor([b'### Introduction to Course' b''], shape=(2,), dtype=string)
tf.Tensor([b'####  Intro to Course' b''], shape=(2,), dtype=string)


## Keras

In [38]:
from tensorflow import keras

### Step 0 : Read Data

### Step 1 : Define Model

In [39]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dense(123, activation = 'relu'),
    tf.keras.layers.Dense(123, activation = 'softmax')
])

### Step 2 : Compline Model

In [ ]:
def rmse(y_true,y_pred):
    return tf.sqrt(tf.reduce_mean(tf.square(y_pred - y_true)))

model.compile(optimizer='adam', loss='mse', metrics=[rmse,'mse'])